X_train:  age                  0
workclass         1836
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_change       0
hours_per_week       0
native_country       0
dtype: int64
Index(['workclass', 'occupation'], dtype='object')
Traceback (most recent call last):
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/graphviz/backend/execute.py", line 85, in run_check
    proc = subprocess.run(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('dot'): PosixPath('dot')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular/train.py", line 99, in <module>
    'model_graph': wandb.Image(graph.render())
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/graphviz/_tools.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/graphviz/rendering.py", line 119, in render
    rendered = self._render(*args, **kwargs)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/graphviz/_tools.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/graphviz/backend/rendering.py", line 320, in render
    capture_output=True)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/graphviz/backend/execute.py", line 88, in run_check
    raise ExecutableNotFound(cmd) from e
graphviz.backend.execute.ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH